### ISSUE TITLE
基于官网的demo例子，我们应该如何获取app(ios)页面的元素呢？

### ISSUE THREAD

**Issue by Li19881204** [macacajs/macaca-ios#26]
it('#4 should go into webview', function() {
    return driver
      .webview()
      .elementById('pushView') //此处id如何获得？
      .tap()
      .sleep(5000)
      .webview()
      .elementById('popView') //此处id如何获得？
      .tap()
      .sleep(5000)
      .takeScreenshot();
  });

**Comment by xudafeng** [comment]
@Li19881204 https://testerhome.com/topics/5054
