### ISSUE TITLE
关于macaca一些疑问

### ISSUE THREAD

**Issue by Li19881204** [macacajs/macaca-ios#27]
1.我看了官网的例子，例子代码driver的下方，有一个webview()和native()这两个方法，这两方法在官网的api中也没有介绍，求这两个方法的含义。
2.在学习过程中，我没有找到像appium那样可以校验期望结果的方法，如assetText()，现在是否支持这个功能？
3.在demo中的login方法代码内，有一个waitForElementByXPath方法，我在官网的api中未找到这个方法，能给一个这个方法详细的说明么？
4.在官网的api中我看到setImplicitWaitTimeout()这个方法，这个方法仅仅是设置智能等待的时间，还是可以直接实现智能等待的功能呢？

**Comment by xudafeng** [comment]
@Li19881204 http://macacajs.github.io/macaca-wd/api/
