### ISSUE TITLE
findElements接口底层调用有问题

### ISSUE THREAD

**Issue by jasonSky** [macacajs/macaca-ios#46]
底层使用selenium-atom接口来实现 每次返回的都是整个elements数组

完全没有使用wda提供的有关elements接口 导致在某个元素集下查找功能缺失
也不能使用查找条件来查找

**Comment by jasonSky** [comment]
@zenzhu

**Comment by ziczhu** [comment]
web 元素是通过 atoms 查找的，native 是用 wda 原生查找的。

**Comment by jasonSky** [comment]
那我查看的源码 怎么每次调用都是用的atom ios
![00b54db4-73ed-e8e5-f8a7-afcc59fbc07f](https://cloud.githubusercontent.com/assets/8477313/21043939/67d12b2a-be34-11e6-98ea-0c570e184c04.png)
![11f94afe-772b-0efe-c0b9-eec1d67f334c](https://cloud.githubusercontent.com/assets/8477313/21043941/68107050-be34-11e6-9f95-346fb81a82c4.png)
![85e1ef01-07fa-120a-d9a0-8d8327790d1d](https://cloud.githubusercontent.com/assets/8477313/21043943/690aa9e4-be34-11e6-85e6-5012c3c9ce67.png)

调试也是这样

**Comment by ziczhu** [comment]
native 的话，是直接把请求代理走了的。

**Comment by jasonSky** [comment]
这是直接router监听过来的  你确定？

xctest-client才是走的proxy吧

**Comment by ziczhu** [comment]
我们会判断当前是 Native 还是 Web 的，然后调用 Proxy 方法的，另外，只用 atoms 也不可能查找 Native 元素啊，那都是纯 js。

**Comment by jasonSky** [comment]
ios setting应用不是native的？

我想知道proxy在哪里进行选择走向 确实没找到 请明示 谢谢了

**Comment by ziczhu** [comment]
```
IOS.prototype.proxyCommand = function *(url, method, body) {
  yield this.autoHandleAlerts();
  return this.proxy.sendCommand(url, method, body);
};
```
然后 webdriver-server 里面会根据当前是不是代理模式来选择直接调用 proxyCommand 方法。

**Comment by jasonSky** [comment]
@zenzhu 是这个吗？
![Uploading {11E27FE2-A1B9-66F4-FFF7-0B41664B23E4}.png…]()

写死了 false

**Comment by ziczhu** [comment]
https://github.com/macacajs/webdriver-server/blob/master/lib/server/controllers/session.js#L92-L107 看看这段。

**Comment by jasonSky** [comment]
![11e27fe2-a1b9-66f4-fff7-0b41664b23e4](https://cloud.githubusercontent.com/assets/8477313/21044961/543e7afe-be39-11e6-8c4c-6ec45243ed62.png)


这样的话就一直都是 不走proxy的

**Comment by ziczhu** [comment]
https://github.com/macacajs/webdriver-server/blob/master/lib/server/responseHandler.js#L35-L52 这段会根据返回来修改当前 proxyMode 的。

**Comment by jasonSky** [comment]
![ef362929-3a48-4163-ffce-aa8b3c0fba22](https://cloud.githubusercontent.com/assets/8477313/21045735/7f526c84-be3c-11e6-905c-2ef8735d50ff.png)

难道这里有问题？

SessionAvalible并没有显式调用 
responseHandler也是返回处理 并不是入口   你说的每次会判断proxyMode来接受请求并没有

这里应该是 yield this.proxyCommand(...); ?

**Comment by ziczhu** [comment]
https://github.com/macacajs/webdriver-server/blob/master/lib/server/router.js#L62
所有请求都过了 SessionAvalible。

**Comment by jasonSky** [comment]
@zenzhu 好的谢谢 终于弄通了 原来是findchildElement没实现 我一直以为findelement和wda对应
