### ISSUE TITLE
npm安装不成功

### ISSUE THREAD

**Issue by grubby2013** [macacajs/macaca-ios#58]
ld: framework not found MobileDevice
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld build/Release/devicelog normal x86_64
(1 failure)
npm ERR! Cannot read property 'pause' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 65
npm ERR! devicelog@1.0.2 preinstall: `xcodebuild`
npm ERR! Exit status 65
npm ERR! 
npm ERR! Failed at the devicelog@1.0.2 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by oosnail** [comment]
同样的问题。。是不是xcode9 没有支持？

**Comment by grubby2013** [comment]
应该是...我不太确定

**Comment by xudafeng** [comment]
升级新版
