### ISSUE TITLE
cnpm I macaca-ios -g 安装报错

### ISSUE THREAD

**Issue by Ct1L** [macacajs/macaca-ios#65]
![1523279926986](https://user-images.githubusercontent.com/29400053/38499934-9dc9319c-3c3b-11e8-8c2a-e759d600890a.jpg)
如图所示
@xudafeng

**Comment by Ct1L** [comment]
本地删除了macaca-ios的驱动之后再重新安装同样报错，cnpm的卸载指令同样无效

**Comment by xudafeng** [comment]
@Ct1L macaca doctor 检查一下
