### ISSUE TITLE
模拟器操作的几点疑惑

### ISSUE THREAD

**Issue by small-tou** [macacajs/macaca-ios#67]
第一个问题：
https://github.com/macacajs/macaca-ios/blob/bed355bb6925888d2bd4f8f006d8f5eee9ca05a9/lib/macaca-ios.js#L325-L335

这里的代码为什么是 先 killAll 然后再 shutdown 当前设备，这样终端会报一个错误：

```
 macaca-ios.js:334:12 [master] pid:9086 Shutdown simulator 5BBB462A-B202-41B1-A64F-4AAE008D958A failed Error: Command failed: xcrun simctl shutdown "5BBB462A-B202-41B1-A64F-4AAE008D958A"
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164):
Unable to shutdown device in current state: Shutdown
```

这里感觉没有必要 killAll 去关掉开着的所有 模拟器。

第二个问题：

https://github.com/macacajs/macaca-ios/blob/bed355bb6925888d2bd4f8f006d8f5eee9ca05a9/lib/macaca-ios.js#L341

首先，如果电脑上有 beta 版 xcode 10，这个 open 不会启动指定的模拟器，而是启动了一个默认的模拟器。
另外，Simulator 里的 boot 和 open，这两个方法为什么用不同性质的命令来实现？这里如果调用 boot 方法是不是就木有问题了。

https://github.com/macacajs/ios-simulator/blob/bb74143f165d2e5bef8ee1db96fc8b05cc6e8dbe/lib/ios-simulator.js#L17-L53

可能是我有其他的因素没有考虑？所以这里是有原因才这样用的吗？

**Comment by xudafeng** [comment]
@xinyu198736 

问题1：逻辑是有些问题，可以把killAll放后面

 https://github.com/macacajs/macaca-ios/blob/bed355bb6925888d2bd4f8f006d8f5eee9ca05a9/lib/macaca-ios.js#L325-L329

如果shutdown失败了，可以再kill一次

**Comment by xudafeng** [comment]
问题2：系统上如果同时有xcode9.x和一个xcode 10beta，应该是会错乱的。

具体问题需要查。
