### ISSUE TITLE
能不能固定macaca-ios依赖的xctestwd版本，xctestwd频繁升级导致macaca-ios经常跑挂

### ISSUE THREAD

**Issue by cary1179** [macacajs/macaca-ios#72]
如题，macaca-ios依赖的`xctestwd`版本是1及以上，每次`xctestwd`在npm升级后，重新安装macaca-ios依赖的`xctestwd`也强制升级了。如果xctestwd的修改有问题，可能就挂了。
可以固定`xctestwd`版本的话，至少不会经常受影响。

**Comment by xudafeng** [comment]
@cary1179 目前还做不到
