### ISSUE TITLE
failed to npm i macaca-ios -g with error

### ISSUE THREAD

**Issue by watonyweng** [macacajs/macaca-ios#74]
** BUILD SUCCEEDED **

> devicelog@1.0.9 install /usr/local/lib/node_modules/macaca-ios/node_modules/devicelog
> node ./scripts/build.js

> xctestwd@1.4.18 install /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd
> node ./scripts/install.js

start to mv /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd-frameworks/Carthage /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd
Carthage is existed: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/Carthage
preparing xctestrun build
User defaults from command line:
    IDEDerivedDataPathOverride = /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/build

xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, OS:latest, name:iPhone 7 }

	The requested device could not be found because no available devices matched the request.

	Ineligible destinations for the "XCTestWDUITests" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }
fs.js:126
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/build/Build/Products'
    at Object.readdirSync (fs.js:795:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/scripts/install.js:119:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/build/Build/Products'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xctestwd@1.4.18 install: `node ./scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xctestwd@1.4.18 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in

> macaca-doctor version: 2.0.18

> Node.js checklist:
> node env: /usr/local/bin/node
> node version: v12.6.0

> iOS checklist:
> macOS version: 10.14.4
> Xcode Command Line Tools is ready, version: 2354.
> xcodebuild version: 10.3
> iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
> ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

**Comment by xudafeng** [comment]
xcode 能正常打开吗?

**Comment by watonyweng** [comment]
@xudafeng Xcode can be opened normally and command line tools have been installed.
> Xcode Version 10.3 (10G8)
> $ xcode-select -v
> xcode-select version 2354.

**Comment by watonyweng** [comment]
I guess it may be that [XCTestWD](https://github.com/macacajs/XCTestWD/blob/master/scripts/install.js#L69) does not adapte the Xcode version just released.

**Comment by iwhyshop** [comment]
the same error,my xcode is 11.0
