### ISSUE TITLE
旧版xcode(10.1)安装2.0.36版本报异常，我看了下似乎是旧版本不支持available这个参数，导致没有找到模拟器列表

### ISSUE THREAD

**Issue by Nicolasyy** [macacajs/macaca-ios#77]
![image](https://user-images.githubusercontent.com/31531639/76595887-c4f1a980-6537-11ea-840d-e4f81af0ca30.png)

**Comment by paradite** [comment]
建议更新一下xcode或者用旧的macaca-ios。xcode老版的支持迟早会停止的。
如果有兴趣可以发个PR暂时兼容一下。对应的逻辑在这里：
https://github.com/macacajs/XCTestWD/pull/164/files

**Comment by Nicolasyy** [comment]
我把available这个去掉，再重新运行可以正常编译过去了

**Comment by paradite** [comment]
fixed via https://github.com/macacajs/XCTestWD/pull/171
