### ISSUE TITLE
Module compiled with Swift 5.2 cannot be imported by the Swift 5.3 compiler

### ISSUE THREAD

**Issue by niyaoyao** [macacajs/macaca-ios#78]
Environment: Version 12.0 (12A7209)
I build and run the XCTestWD project in node_module after I run `DEVELOPMENT_TEAM_ID=XXXXXXXX npm i macaca-ios -g` in terminal, it comes out this error.

It seems that the framework linked in project was compiled with Swift5.2 and not be compatible with Swift5.3(Xcode 12). So, how can I  fix the issue?

**Comment by niyaoyao** [comment]
Hey, guys. It seems that you should enable  BUILD_LIBRARY_FOR_DISTRIBUTION = YES, and recompile the framework Swifter then release the XCTestWD with the macaca-ios tool to compatible with Xcode12. 

Ref link:
https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler

I've tried to use carthage to update framework and failed again. Command line below.
```
➜  xctestwd carthage update --platform iOS --no-use-binaries
*** Fetching CocoaLumberjack
*** Fetching AEXML
*** Fetching Nimble
*** Fetching SwiftyJSON
*** Fetching swifter
*** Checking out AEXML at "4.5.0"
*** Checking out CocoaLumberjack at "3.4.2"
*** Checking out Nimble at "v8.0.1"
*** Checking out Fuzi at "b26786259f13b8a83eaff0ac46dd052c18960df5"
*** Checking out swifter at "1.4.3"
*** Checking out SwiftyJSON at "4.2.0"
*** xcodebuild output can be found in /var/folders/f_/9j_l20dn42l15lmsy7fw8mbh0000gn/T/carthage-xcodebuild.a91H97.log
*** Building scheme "AEXML iOS" in AEXML.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/yao/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/AEXML/4.5.0/Build/Intermediates.noindex/ArchiveIntermediates/AEXML\ iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AEXML.framework/AEXML /Users/yao/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/AEXML/4.5.0/Build/Products/Release-iphonesimulator/AEXML.framework/AEXML -output /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/Carthage/Build/iOS/AEXML.framework/AEXML

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/f_/9j_l20dn42l15lmsy7fw8mbh0000gn/T/carthage-xcodebuild.a91H97.log
```

@paradite @xudafeng Thanks a lot~

**Comment by niyaoyao** [comment]
Hey guys, I finally find out the solution for Xcode12 carthage build frameworks.

Here is the ref link:
https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323

```
#!/usr/bin/env bash

# carthage.sh
# Usage example: ./carthage.sh build --platform iOS

set -euo pipefail

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

# For Xcode 12 make sure EXCLUDED_ARCHS is set to arm architectures otherwise
# the build will fail on lipo due to duplicate architectures.
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig
echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"
carthage "$@"
```
The script above is worked for me. Hope it can help you to fix the issue of the XCTestWD driver project.
@paradite @paradite Thanks a lot.

**Comment by paradite** [comment]
> Hey guys, I finally find out the solution for Xcode12 carthage build frameworks.
> 
> Here is the ref link:
> [Carthage/Carthage#3019 (comment)](https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323)
> 
> ```
> #!/usr/bin/env bash
> 
> # carthage.sh
> # Usage example: ./carthage.sh build --platform iOS
> 
> set -euo pipefail
> 
> xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
> trap 'rm -f "$xcconfig"' INT TERM HUP EXIT
> 
> # For Xcode 12 make sure EXCLUDED_ARCHS is set to arm architectures otherwise
> # the build will fail on lipo due to duplicate architectures.
> echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig
> echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig
> 
> export XCODE_XCCONFIG_FILE="$xcconfig"
> carthage "$@"
> ```
> 
> The script above is worked for me. Hope it can help you to fix the issue of the XCTestWD driver project.
> @paradite @paradite Thanks a lot.

thank you so much, will take a look. let's track it here:
https://github.com/alibaba/macaca/issues/985

**Comment by niyaoyao** [comment]
Wow! It's so great to hear that Macaca is  compatible with Xcode12. I will upgrade for our own project. Thank you so much.
